### ISSUE TITLE
Weird syntax highlighting

### ISSUE THREAD

**Issue by tudorache** [protegeproject/snap-sparql-query#2]
Happened on multiple Windows computers.

![image004](https://cloud.githubusercontent.com/assets/2709502/10200460/7102a92a-675b-11e5-8c6d-134ed80de5bf.jpg)

**Comment by tudorache** [comment]
Another example from  Windows machine:

![cidifebj](https://cloud.githubusercontent.com/assets/2709502/10201107/24992eb6-675f-11e5-9579-fc976b2da0db.png)

**Comment by csnyulas** [comment]
This strange bug was there for such a long time, but I think I just figured out what the problem may be!
From the fact that the syntax highlight is being shifted by one additional character to the right on each line, it is probably due to the invisible \r character in the line ending: "\r\n" vs. "\n"

**Comment by tudorache** [comment]
Users reported that this bug appears also in the restriction editor. (reported by windows users)

**Comment by tudorache** [comment]
Protege 5.0.0-b24 snapshot

The weird syntax highlighting is still there.

Windows 10.

![snap](https://cloud.githubusercontent.com/assets/2709502/13695271/c7e1b336-e711-11e5-8897-bee36b686259.png)

**Comment by rsgoncalves** [comment]
Got this in Windows 7 as well, on P5 beta 24.
